# Generated by Django 3.2.9 on 2022-01-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmsuj_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
