# Generated by Django 3.2.9 on 2022-04-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmsuj_website', '0003_page_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='site',
            field=models.CharField(choices=[('OSSM', 'OSSM'), ('KMSUJ', 'KMS UJ')], default='KMSUJ', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('name', 'site')},
        ),
    ]
