# Generated by Django 3.2.9 on 2022-05-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmsuj_website', '0005_alter_page_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilingualPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('title_polish', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, max_length=100000)),
                ('content_polish', models.TextField(blank=True, max_length=100000)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(default='none', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='site',
            field=models.CharField(choices=[('KMSUJ', 'KMS UJ'), ('OSSM', 'OSSM')], default='KMSUJ', max_length=9),
        ),
    ]
