# Generated by Django 3.2.9 on 2022-05-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmsuj_website', '0006_auto_20220513_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilingualpage',
            name='name',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='site',
            field=models.CharField(choices=[('OSSM', 'OSSM'), ('KMSUJ', 'KMS UJ')], default='KMSUJ', max_length=9),
        ),
    ]
